### ISSUE TITLE
Can't work after upgrade `rust-bitcoin` to 0.32.0

### ISSUE THREAD

**Issue by lshoo** [panicfarm/multisig-test#1]
Very good examples, thank you very much.

When I upgraded  `rust-bitcoin` to the latest `0.32.0` of example, some api's have been removed (e.g. `segwit_signature_hash`， `Deprecated since 0.31.0: use (p2wpkh|p2wsh)_signature_hash instead`), and when replacing it with the 0.32.0 counterpart (`p2wpkh_signature_hash`), I got a runtime error.

In the p2wpkh example the following statement gives an error at runtime:

```rust
let sighash = cache
        .p2wpkh_signature_hash(inp_idx, &script_code, Amount::from_sat(value), sig.sighash_type)
        .expect("failed to compute sighash");
```

the error info: `failed to compute sighash: NotP2wpkhScript`.

I changed the version of rust-bitcoin to 0.31.2 and got the same error if using `p2wpkh_signature_hash` api.
But 0.31.2 also has `segwit_signature_hash` api, when use `segwit_signature_hash` api to run it, it works.

My problem is:
1. The docs of `rust-bitcoin` says that `segwit_signature_hash` is replaced by `p2wpkh_signature_hash`, but the behavior of these two api's is completely different, `p2wpkh_signature_hash` has only 1 more line of code to get the `ScriptBuf`:
```
let script_code = script_pubkey.p2wpkh_script_code().ok_or(Error::NotP2wpkhScript)? ;
```

This is where the error comes in, the data in the example is legal in 0.30 or 0.31 with script_code, why is it not legal with 0.32.0?

2. How can I change the code to work correctly in 0.32.0?

Thanks

Best Regards

lshoo

**Comment by panicfarm** [comment]
Hi @lshoo . Thanks for trying to update.

In the new `p2wpkh_signature_hash()` API, `script_code = spk.p2wpkh_script_code()` is no longer needed. 
From [BIP 143](https://github.com/bitcoin/bips/blob/99701f68a88ce33b2d0838eb84e115cef505b4c2/bip-0143.mediawiki) notice the difference:
```
scriptPubKey:  0 <20-byte key hash>
scriptCode: 0x1976a914{20-byte key hash}88ac
```
Both can be constructed from the pubKeyHash.

I updated the code and pushed the new version.

**Comment by lshoo** [comment]
Great, it works!
Thanks @panicfarm
